---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: pixie-operator
  namespace: pl
spec:
  interval: 5m0s
  url: https://artifacts.px.dev/helm_charts/operator
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: pixie-operator
  namespace: pl
spec:
  driftDetection:
    mode: enabled
  chart:
    spec:
      chart: pixie-operator-chart
      sourceRef:
        kind: HelmRepository
        name: pixie-operator
  interval: 1h0m0s
  values:
    clusterName: ripple-transfer
  valuesFrom:
    - kind: Secret
      name: pixie-deployment-key
