apiVersion: "cilium.io/v2alpha1"
kind: CiliumL2AnnouncementPolicy
metadata:
  name: load-balancer
spec:
  serviceSelector:
    matchLabels:
      # Hassle: Specifying a custom label for the announced services makes sense, otherwise we get
      # way too many leases. This way, we can restrict L2 announcements to the ingresses and gateways
      loom-lang.announce: l2
  nodeSelector:
    matchExpressions:
      - key: node-role.kubernetes.io/control-plane
        operator: DoesNotExist
  loadBalancerIPs: true
