---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: trivy
  namespace: trivy-system
spec:
  interval: 30m
  targetNamespace: trivy-system
  releaseName: trivy
  chart:
    spec:
      chart: trivy-operator
      version: "0.x"
      sourceRef:
        kind: HelmRepository
        name: aqua
        namespace: trivy-system
      interval: 12h
  values:
    serviceMonitor:
      enabled: true
    nodeCollector:
      useNodeSelector: false
