---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: core
  namespace: flux-infrastructure
spec:
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: ripple-infra
  path: ./infrastructure/core
  prune: true
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: networking
  namespace: flux-infrastructure
spec:
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: ripple-infra
  dependsOn:
    - name: core
      namespace: flux-infrastructure
  path: ./infrastructure/networking
  prune: true
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: storage
  namespace: flux-infrastructure
spec:
  interval: 5m
  dependsOn:
    - name: networking
      namespace: flux-infrastructure
    - name: core
      namespace: flux-infrastructure
  sourceRef:
    kind: GitRepository
    name: ripple-infra
  path: ./infrastructure/storage
  prune: true
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: monitoring
  namespace: flux-infrastructure
spec:
  interval: 5m
  timeout: 10m
  dependsOn:
    - name: networking
      namespace: flux-infrastructure
    - name: storage
      namespace: flux-infrastructure
    - name: core
      namespace: flux-infrastructure
  sourceRef:
    kind: GitRepository
    name: ripple-infra
  path: ./infrastructure/monitoring
  prune: true
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ingress
  namespace: flux-infrastructure
spec:
  interval: 5m
  dependsOn:
    - name: networking
      namespace: flux-infrastructure
    - name: monitoring
      namespace: flux-infrastructure
    - name: core
      namespace: flux-infrastructure
  sourceRef:
    kind: GitRepository
    name: ripple-infra
  path: ./infrastructure/ingress
  prune: true
  wait: true
