---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: storage-minio
  namespace: flux-infrastructure
spec:
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: loom-infra
  path: ./infrastructure/storage/minio
  prune: true
  wait: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age
