# three node (two workers) cluster config
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: ripple
featureGates:
  SidecarContainers: true
nodes:
  - role: control-plane
    image: kindest/node:v1.29.2@sha256:51a1434a5397193442f0be2a297b488b6c919ce8a3931be0ce822606ea5ca245
    # Hassle: local storage capacity isolation is disabled by default for rootless kind containers, making
    # it impossible for minio pods to be scheduled: https://github.com/kubernetes-sigs/kind/issues/3359
    kubeadmConfigPatches:
      - |
        kind: KubeletConfiguration
        localStorageCapacityIsolation: true
    extraMounts:
      - containerPath: /var/lib/kubelet/config.json
        hostPath: ./.cert/secret.json
  - role: worker
    image: kindest/node:v1.29.2@sha256:51a1434a5397193442f0be2a297b488b6c919ce8a3931be0ce822606ea5ca245
    extraMounts:
      - containerPath: /var/lib/kubelet/config.json
        hostPath: ./.cert/secret.json
  - role: worker
    image: kindest/node:v1.29.2@sha256:51a1434a5397193442f0be2a297b488b6c919ce8a3931be0ce822606ea5ca245
    extraMounts:
      - containerPath: /var/lib/kubelet/config.json
        hostPath: ./.cert/secret.json
