# three node (two workers) cluster config
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: ripple
featureGates:
  SidecarContainers: true
containerdConfigPatches:
- |-
  [plugins."io.containerd.grpc.v1.cri".registry.mirrors."docker.io"]
    endpoint = ["http://proxy-docker-hub:5000"]
- |-
  [plugins."io.containerd.grpc.v1.cri".registry.mirrors."quay.io"]
    endpoint = ["http://proxy-quay:5000"]
- |-
  [plugins."io.containerd.grpc.v1.cri".registry.mirrors."k8s.gcr.io"]
    endpoint = ["http://proxy-k8s-gcr:5000"]
- |-
  [plugins."io.containerd.grpc.v1.cri".registry.mirrors."gcr.io"]
    endpoint = ["http://proxy-gcr:5000"]
nodes:
  - role: control-plane
    image: kindest/node:v1.31.0@sha256:53df588e04085fd41ae12de0c3fe4c72f7013bba32a20e7325357a1ac94ba865
    # Hassle: local storage capacity isolation is disabled by default for rootless kind containers, making
    # it impossible for minio pods to be scheduled: https://github.com/kubernetes-sigs/kind/issues/3359
    kubeadmConfigPatches:
      - |
        kind: KubeletConfiguration
        localStorageCapacityIsolation: true
    extraMounts:
      - containerPath: /var/lib/kubelet/config.json
        hostPath: ./.cert/secret.json
  - role: worker
    image: kindest/node:v1.31.0@sha256:53df588e04085fd41ae12de0c3fe4c72f7013bba32a20e7325357a1ac94ba865
    extraMounts:
      - containerPath: /var/lib/kubelet/config.json
        hostPath: ./.cert/secret.json
  - role: worker
    image: kindest/node:v1.31.0@sha256:53df588e04085fd41ae12de0c3fe4c72f7013bba32a20e7325357a1ac94ba865
    extraMounts:
      - containerPath: /var/lib/kubelet/config.json
        hostPath: ./.cert/secret.json
  - role: worker
    image: kindest/node:v1.31.0@sha256:53df588e04085fd41ae12de0c3fe4c72f7013bba32a20e7325357a1ac94ba865
    extraMounts:
      - containerPath: /var/lib/kubelet/config.json
        hostPath: ./.cert/secret.json
