# three node (two workers) cluster config
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: ripple
featureGates:
  SidecarContainers: true
nodes:
  - role: control-plane
    image: kindest/node:v1.30.0@sha256:047357ac0cfea04663786a612ba1eaba9702bef25227a794b52890dd8bcd692e
    # Hassle: local storage capacity isolation is disabled by default for rootless kind containers, making
    # it impossible for minio pods to be scheduled: https://github.com/kubernetes-sigs/kind/issues/3359
    kubeadmConfigPatches:
      - |
        kind: KubeletConfiguration
        localStorageCapacityIsolation: true
    extraMounts:
      - containerPath: /var/lib/kubelet/config.json
        hostPath: ./.cert/secret.json
  - role: worker
    image: kindest/node:v1.30.0@sha256:047357ac0cfea04663786a612ba1eaba9702bef25227a794b52890dd8bcd692e
    extraMounts:
      - containerPath: /var/lib/kubelet/config.json
        hostPath: ./.cert/secret.json
  - role: worker
    image: kindest/node:v1.30.0@sha256:047357ac0cfea04663786a612ba1eaba9702bef25227a794b52890dd8bcd692e
    extraMounts:
      - containerPath: /var/lib/kubelet/config.json
        hostPath: ./.cert/secret.json
  - role: worker
    image: kindest/node:v1.30.0@sha256:047357ac0cfea04663786a612ba1eaba9702bef25227a794b52890dd8bcd692e
    extraMounts:
      - containerPath: /var/lib/kubelet/config.json
        hostPath: ./.cert/secret.json
