---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: gateway
  namespace: networking-gateway
spec:
  interval: 5m
  timeout: 10m
  driftDetection:
    mode: enabled
  chart:
    spec:
      chart: gateway-helm
      version: "v0.0.0-latest"
      sourceRef:
        kind: HelmRepository
        name: gateway
        namespace: networking-gateway
      interval: 1m
