---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: gateway
  namespace: networking-gateway
spec:
  interval: 5m
  driftDetection:
    mode: enabled
  chart:
    spec:
      chart: gateway-helm
      version: "v1.0.1"
      sourceRef:
        kind: HelmRepository
        name: gateway
        namespace: networking-gateway
      interval: 1m
  values:
    logging:
      level: debug
