apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: projectcontour

resources:
  - https://raw.githubusercontent.com/projectcontour/contour/release-1.28.0-rc.1/examples/render/contour-gateway-provisioner.yaml
