apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ingress

resources:
  - https://app.getambassador.io/yaml/emissary/3.8.2/emissary-crds.yaml
patches:
  # Hassle: Emissary creates the namespace in its CRDs. This means we need to patch in the
  # Linkerd annotations and since we'd like to have an `ingress` namespace instead of the default
  # `emissary-system` one, we'll also patch the name.
  - patch: |-
      - op: replace
        path: /metadata/name
        value: ingress
    target:
      kind: Namespace
      name: emissary-system
