---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: istio-base
  namespace: istio-system
spec:
  interval: 5m
  driftDetection:
    mode: enabled
  chart:
    spec:
      chart: base
      version: "1.21.0-beta.1"
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: istio-system
      interval: 1m
