---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istio-base
  namespace: istio-system
spec:
  interval: 5m
  # Hassle: istio-base mutates resources on Helm install which triggers a lot of drift correction steps
  # driftDetection:
  #   mode: enabled
  chart:
    spec:
      chart: base
      version: "1.23.x"
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: istio-system
      interval: 1m
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istio-cni
  namespace: istio-system
spec:
  interval: 5m
  driftDetection:
    mode: enabled
  dependsOn:
    - name: istio-base
      namespace: istio-system
  chart:
    spec:
      chart: cni
      version: "1.23.x"
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: istio-system
      interval: 1m
  values:
    profile: ambient
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istiod
  namespace: istio-system
spec:
  interval: 5m
  # driftDetection:
  #   mode: enabled
  dependsOn:
    - name: istio-cni
      namespace: istio-system
  chart:
    spec:
      chart: istiod
      version: "1.23.x"
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: istio-system
      interval: 1m
  values:
    profile: ambient
    env:
      PILOT_ENABLE_IP_AUTOALLOCATE: "true"
      ENABLE_INBOUND_RETRY_POLICY: "true"
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ztunnel
  namespace: istio-system
spec:
  interval: 5m
  driftDetection:
    mode: enabled
  dependsOn:
    - name: istiod
      namespace: istio-system
  chart:
    spec:
      chart: ztunnel
      version: "1.23.x"
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: istio-system
      interval: 1m
