---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: linkerd-jaeger
  namespace: linkerd-jaeger
spec:
  interval: 30m
  targetNamespace: linkerd-jaeger
  releaseName: linkerd-jaeger
  chart:
    spec:
      version: "30.x"
      chart: linkerd-jaeger
      sourceRef:
        kind: HelmRepository
        name: linkerd
        namespace: linkerd
      interval: 12h
  values:
    collector:
      enabled: false
    jaeger:
      enabled: false
    webhook:
      collectorSvcAddr: grafana-tempo-distributor.grafana.svc.cluster.local:55678
      collectorSvcAccount: grafana-tempo
