---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: k8s-monitoring
  namespace: grafana-k8s-monitoring
spec:
  interval: 30m
  chart:
    spec:
      chart: k8s-monitoring
      version: "1.x"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: grafana-k8s-monitoring
      interval: 12h
  values:
    cluster:
      name: dev
    externalServices:
      prometheus:
        host: http://mimir-gateway.grafana-mimir.svc
        writeEndpoint: /api/v1/push
        queryEndpoint: /prometheus/api/v1/query
        authMode: none
      loki:
        host: http://loki-gateway.grafana-loki.svc
        authMode: none
      pyroscope:
        host: http://pyroscope-distributor.grafana-pyroscope.svc:4040
        authMode: none
      tempo:
        host: http://tempo-distributor.grafana-tempo.svc
        authMode: none
    profiles:
      enabled: true
    traces:
      enabled: true
    prometheus-operator-crds:
      enabled: false
    opencost:
      # TODO: Set up basic auth for this to work
      enabled: false
      opencost:
        prometheus:
          external:
            url: http://mimir-gateway.grafana-mimir.svc/prometheus
