---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: utilities-reflector
  namespace: flux-infrastructure
spec:
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: ripple-infra
  path: ./infrastructure/utilities/reflector
  prune: true
  wait: true
