apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: grafana-mimir

resources:
  - namespace.yaml
  - minio.yaml

secretGenerator:
  - name: minio-root
    namespace: grafana-mimir
    envs:
      - minio.env

configurations:
  - kustomizeconfig.yaml
