---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minio
  namespace: grafana-mimir
spec:
  interval: 30m
  chart:
    spec:
      chart: tenant
      version: "5.x"
      sourceRef:
        kind: HelmRepository
        name: minio-operator
        namespace: minio
      interval: 12h
  values:
    tenant:
      name: grafana-mimir
      pools:
        - servers: 1
          name: mimir-pool
          volumesPerServer: 1
          size: 1Gi
          storageClassName: standard
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
            fsGroupChangePolicy: "OnRootMismatch"
            runAsNonRoot: true
          containerSecurityContext:
            runAsUser: 1000
            runAsGroup: 1000
            runAsNonRoot: true
      buckets:
        - name: mimir-ruler
        - name: mimir-blocks
        - name: mimir-alertmanager
      metrics:
        enabled: true
        port: 9000
        protocol: http
      certificate:
        requestAutoCert: false
  valuesFrom:
    - kind: Secret
      name: minio-root
      valuesKey: accessKey
      targetPath: secrets.accessKey
    - kind: Secret
      name: minio-root
      valuesKey: secretKey
      targetPath: secrets.secretKey
