---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: gitops-grant
  namespace: flux-system
spec:
  from:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      namespace: api-gateway
  to:
    - group: ""
      kind: Service
      name: weave-gitops-dashboard
