---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cilium
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      chart: cilium
      version: "1.14.x"
      sourceRef:
        kind: HelmRepository
        name: cilium
        namespace: kube-system
      interval: 1m
  valuesFrom:
    - kind: ConfigMap
      name: cilium-values
    # We actually upgrade the Cilium installation in-place, by enabling mTLS for Hubble after the bootstrap
    # is complete. This allows us to install cert-manager before this step.
    - kind: ConfigMap
      name: cilium-values-tls
