apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - repository.yaml
  - cilium.yaml
  - cilium-trust-anchor.yaml
  - l2-announcement.yaml
  - load-balancer-ips.yaml
  - hubble-grant.yaml
configMapGenerator:
  - name: cilium-values
    namespace: kube-system
    files:
      - values.yaml
  - name: cilium-values-tls
    namespace: kube-system
    files:
      - values.yaml=values-tls.yaml
configurations:
  - kustomizeconfig.yaml
