apiVersion: cilium.io/v2alpha1
kind: CiliumL2AnnouncementPolicy
metadata:
  name: load-balancer
  namespace: cilium
spec:
  # serviceSelector:
  #   matchLabels:
  #     # Hassle: Envoy Gateway deploys the LB in the namespace where it is installed in,
  #     # not the namespace of the gateway
  #     io.kubernetes.service.namespace: networking-gateway
  loadBalancerIPs: true
