apiVersion: cilium.io/v2alpha1
kind: CiliumL2AnnouncementPolicy
metadata:
  name: load-balancer
  namespace: cilium
spec:
  serviceSelector:
    matchLabels:
      io.kubernetes.service.namespace: api-gateway
  loadBalancerIPs: true
