apiVersion: cilium.io/v2alpha1
kind: CiliumL2AnnouncementPolicy
metadata:
  name: load-balancer
  namespace: kube-system
spec:
  serviceSelector:
    matchLabels:
      io.kubernetes.service.namespace: networking-gateway
  loadBalancerIPs: true
