---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: monitoring-grafana
  namespace: flux-infrastructure
spec:
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: ripple-infra
  path: ./infrastructure/monitoring/grafana
  prune: true
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: monitoring-mimir
  namespace: flux-infrastructure
spec:
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: ripple-infra
  path: ./infrastructure/monitoring/mimir
  prune: true
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: monitoring-linkerd-viz
  namespace: flux-infrastructure
spec:
  interval: 5m
  dependsOn:
    - name: monitoring-grafana
      namespace: flux-infrastructure
  sourceRef:
    kind: GitRepository
    name: ripple-infra
  path: ./infrastructure/monitoring/linkerd-viz
  prune: true
  wait: true
  timeout: 10m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: monitoring-linkerd-jaeger
  namespace: flux-infrastructure
spec:
  interval: 5m
  dependsOn:
    - name: monitoring-grafana
      namespace: flux-infrastructure
  sourceRef:
    kind: GitRepository
    name: ripple-infra
  path: ./infrastructure/monitoring/linkerd-jaeger
  prune: true
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: monitoring-weave-gitops
  namespace: flux-infrastructure
spec:
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: ripple-infra
  path: ./infrastructure/monitoring/weave-gitops
  prune: true
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: monitoring-kubernetes-dashboard
  namespace: flux-infrastructure
spec:
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: ripple-infra
  path: ./infrastructure/monitoring/kubernetes-dashboard
  prune: true
  wait: true
