---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: monitoring-weave-gitops
  namespace: flux-infrastructure
spec:
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: ripple-infra
  path: ./infrastructure/monitoring/weave-gitops
  prune: true
  wait: true
---

