---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: monitoring-weave-gitops
  namespace: flux-infrastructure
spec:
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: ripple-infra
  path: ./infrastructure/monitoring/weave-gitops
  prune: true
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: monitoring-grafana-mimir
  namespace: flux-infrastructure
spec:
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: ripple-infra
  path: ./infrastructure/monitoring/grafana-mimir
  prune: true
  wait: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: monitoring-grafana-tempo
  namespace: flux-infrastructure
spec:
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: ripple-infra
  path: ./infrastructure/monitoring/grafana-tempo
  prune: true
  wait: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: monitoring-grafana-loki
  namespace: flux-infrastructure
spec:
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: ripple-infra
  path: ./infrastructure/monitoring/grafana-loki
  prune: true
  wait: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: monitoring-grafana
  namespace: flux-infrastructure
spec:
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: ripple-infra
  dependsOn:
    - name: monitoring-grafana-tempo
      namespace: flux-infrastructure
    - name: monitoring-grafana-mimir
      namespace: flux-infrastructure
    - name: monitoring-grafana-loki
      namespace: flux-infrastructure
  path: ./infrastructure/monitoring/grafana
  prune: true
  wait: true
