---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minio
  namespace: grafana-loki
spec:
  interval: 30m
  chart:
    spec:
      chart: tenant
      version: "6.x"
      sourceRef:
        kind: HelmRepository
        name: minio-operator
        namespace: minio
      interval: 12h
  values:
    tenant:
      name: grafana-loki
      pools:
        - name: loki-pool
          servers: 1
          volumesPerServer: 1
          size: "1073741824"
          storageClassName: standard
          runtimeClassName: ""
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
            fsGroupChangePolicy: "OnRootMismatch"
            runAsNonRoot: true
          containerSecurityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            runAsUser: 1000
            runAsGroup: 1000
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
      buckets:
        - name: loki-ruler
        - name: loki-chunks
        - name: loki-admin
      metrics:
        enabled: true
        port: 9000
        protocol: http
      certificate:
        requestAutoCert: false
      env:
        - name: MINIO_STORAGE_CLASS_STANDARD
          value: EC:0
        - name: MINIO_STORAGE_CLASS_RRS
          value: EC:0
  valuesFrom:
    - kind: Secret
      name: minio-root
      valuesKey: accessKey
      targetPath: tenant.configSecret.accessKey
    - kind: Secret
      name: minio-root
      valuesKey: secretKey
      targetPath: tenant.configSecret.secretKey
