---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: minio
  namespace: minio
spec:
  interval: 30m
  driftDetection:
    mode: enabled
  chart:
    spec:
      version: "12.x"
      chart: minio
      sourceRef:
        kind: HelmRepository
        name: minio
      interval: 12h
  values:
    auth:
      existingSecret: minio-root
    # TODO: create buckets at the place of usage
    defaultBuckets: "tempo-traces;loki-chunks;loki-ruler;loki-admin;mimir-rules;mimir-blocks"
