---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minio-operator
  namespace: minio
spec:
  interval: 30m
  targetNamespace: minio
  releaseName: minio-operator
  chart:
    spec:
      chart: operator
      version: "6.x"
      sourceRef:
        kind: HelmRepository
        name: minio-operator
        namespace: minio
      interval: 12h
