---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: grafana-loki
  namespace: grafana
spec:
  interval: 30m
  timeout: 15m
  driftDetection:
    mode: enabled
  chart:
    spec:
      chart: loki
      version: "5.x"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: grafana
      interval: 12h
  values:
    loki:
      commonConfig:
        replication_factor: 3
      structuredConfig:
        auth_enabled: false
      # Hassle: This storage configuration is just marginally different and mutually incompatible
      # from Tempo's.
      storage:
        type: s3
        bucketNames:
          chunks: loki-chunks
          ruler: loki-ruler
          admin: loki-admin
        s3:
          # Hassle: Note the dot at the end of the endpoint. Without it, Loki produces URLs in the form of
          # <bucket>.<endpoint> instead of the correct <endpoint>/<bucket>
          endpoint: "minio.minio.svc.cluster.local.:9000"
          insecure: true
          s3ForcePathStyle: true
    # Hassle: This is a temporary compromise to get something working. The distributed version has proven very
    # difficult to get working with very unhelpful error messages and basically no documenation.
    # TODO: Move to microservice-based Loki
    singleBinary:
      replicas: 3
      # Hassle: Loki, by default has hard anti-affinity rules that prevent two pods from being scheduled on the
      # same node. This is perfect for a production system, but on a 2-worker Kind cluster it makes the deployment
      # impossible.
      affinity: null
    # TODO: We turned off quite a few things here to get a deployment up and running. Re-enable service and self monitoring
    monitoring:
      dashboards:
        annotations:
          grafana.io/folder: Loki
        labels:
          grafana.io/dashboard: "true"
      serviceMonitor:
        enabled: false
        metricsInstance:
          enabled: false
      selfMonitoring:
        enabled: false
        grafanaAgent:
          installOperator: false
      lokiCanary:
        enabled: false
    test:
      enabled: false
  valuesFrom:
    - kind: Secret
      name: minio-root
      valuesKey: root-user
      targetPath: loki.storage.s3.accessKeyId
    - kind: Secret
      name: minio-root
      valuesKey: root-password
      targetPath: loki.storage.s3.secretAccessKey
