---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: core-prometheus-crds
  namespace: flux-infrastructure
spec:
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: ripple-infra
  path: ./infrastructure/core/prometheus-crds
  prune: true
  wait: true
