---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: tls-gateway
  namespace: ingress-infra
  annotations:
    cert-manager.io/issuer: letsencrypt
    cert-manager.io/private-key-rotation-policy: Always
    # Hassle: Need to work around: https://github.com/istio/istio/issues/50983
    metallb.universe.tf/loadBalancerIPs: "10.89.255.50"
spec:
  gatewayClassName: istio
  listeners:
    - name: https-wildcard
      protocol: HTTPS
      port: 443
      hostname: "*.ripple-transfer.dev"
      tls:
        mode: Terminate
        certificateRefs:
          - name: ripple-transfer-dev-tls
