---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: tls-gateway
  namespace: ingress-infra
  annotations:
    cert-manager.io/issuer: letsencrypt
    cert-manager.io/private-key-rotation-policy: Always
spec:
  gatewayClassName: eg
  listeners:
    - name: https-wildcard
      protocol: HTTPS
      port: 443
      hostname: "*.ripple-transfer.dev"
      tls:
        mode: Terminate
        certificateRefs:
          - name: ripple-transfer-dev-tls
  infrastructure:
    annotations:
      metallb.universe.tf/loadBalancerIPs: "10.89.255.50"
