apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ingress-infra

resources:
  - namespace.yaml
  - cloudflare-api-key.yaml
  - gateway.yaml
  - letsencrypt-issuer.yaml
  - routes.yaml
  - telemetry.yaml
