---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cilium-trust-anchor
  namespace: kube-system
spec:
  isCA: true
  duration: 87660h
  renewBefore: 720h
  commonName: root.cilium.io
  secretName: cilium-trust-anchor
  privateKey:
    algorithm: ECDSA
    rotationPolicy: Always
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
  subject:
    organizations:
      - Loom
    organizationalUnits:
      - cilium
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: cilium-trust-anchor
  namespace: kube-system
spec:
  ca:
    secretName: cilium-trust-anchor
