---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: networking-cert-manager
  namespace: flux-infrastructure
spec:
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: ripple-infra
  path: ./infrastructure/networking/cert-manager
  prune: true
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: networking-cilium
  namespace: flux-infrastructure
spec:
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: ripple-infra
  path: ./infrastructure/networking/cilium
  prune: true
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: networking-linkerd-base
  namespace: flux-infrastructure
spec:
  interval: 5m
  dependsOn:
    - name: networking-cilium
      namespace: flux-infrastructure
    - name: networking-cert-manager
      namespace: flux-infrastructure
  sourceRef:
    kind: GitRepository
    name: ripple-infra
  path: ./infrastructure/networking/linkerd-base
  prune: true
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: networking-linkerd
  namespace: flux-infrastructure
spec:
  interval: 5m
  dependsOn:
    - name: networking-linkerd-base
      namespace: flux-infrastructure
  sourceRef:
    kind: GitRepository
    name: ripple-infra
  path: ./infrastructure/networking/linkerd
  prune: true
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: networking-linkerd-smi
  namespace: flux-infrastructure
spec:
  interval: 5m
  dependsOn:
    - name: networking-linkerd
      namespace: flux-infrastructure
  sourceRef:
    kind: GitRepository
    name: ripple-infra
  path: ./infrastructure/networking/linkerd-smi
  prune: true
  wait: true
