# Hassle: The ability to expose services under a path, instead of a subdomain varies greatly between
# the different services. Grafana supports this use-case very nicely, while kubernetes-dashboard does
# not at all. For the sake of consistency, we just using subdomains for all of them.
---
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: weave-gitops-dashboard
  namespace: ingress
spec:
  hostname: "gitops.ripple-transfer.dev"
  prefix: /
  service: weave-gitops-dashboard.flux-system:9001
---
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: hubble-api
  namespace: ingress
spec:
  hostname: "hubble.ripple-transfer.dev"
  prefix: /api/
  rewrite: /api/
  # Hassle: Hubble UI is using HTTP streaming to get network flow updates to the UI.
  # The automatic timeout kills this connection, leading to a broken UI and reconnect
  # attempts every few seconds.
  timeout_ms: 0
  service: hubble-ui.kube-system:80
---
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: hubble
  namespace: ingress
spec:
  hostname: "hubble.ripple-transfer.dev"
  prefix: /
  service: hubble-ui.kube-system:80
