---
apiVersion: v1
kind: Namespace
metadata:
  name: flux-infrastructure
  annotations:
    linkerd.io/inject: enabled
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: ripple-infra
  namespace: flux-infrastructure
spec:
  interval: 1m0s
  ref:
    branch: master
  url: https://github.com/ripple-transfer/ripple-infra.git
