---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tempo
  namespace: grafana-tempo
spec:
  interval: 30m
  dependsOn:
    - name: minio
      namespace: grafana-tempo
  chart:
    spec:
      chart: tempo-distributed
      version: "1.x"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: grafana-tempo
      interval: 12h
  values:
    gateway:
      enabled: true
    metricsGenerator:
      enabled: true
      config:
        storage:
          remote_write_add_org_id_header: false
          remote_write:
            - url: http://mimir-gateway.grafana-mimir.svc/api/v1/push
              send_exemplars: true
    traces:
      otlp:
        grpc:
          enabled: true
        http:
          enabled: true
      zipkin:
        enabled: true
      jaeger:
        thriftHttp:
          enabled: true
      opencensus:
        enabled: true
    storage:
      trace:
        backend: s3
        s3:
          bucket: tempo-traces
          endpoint: minio.grafana-tempo.svc
          insecure: true
    global_overrides:
      metrics_generator_processors: [service-graphs, span-metrics]
  valuesFrom:
    - kind: Secret
      name: minio-root
      valuesKey: accessKey
      targetPath: storage.trace.s3.access_key
    - kind: Secret
      name: minio-root
      valuesKey: secretKey
      targetPath: storage.trace.s3.secret_key
