---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: linkerd-viz
  namespace: linkerd-viz
spec:
  interval: 30m
  targetNamespace: linkerd-viz
  releaseName: linkerd-viz
  driftDetection:
    mode: enabled
  chart:
    spec:
      version: "30.x-edge"
      chart: linkerd-viz
      sourceRef:
        kind: HelmRepository
        name: linkerd
        namespace: linkerd
      interval: 12h
  values:
    grafana:
      externalUrl: https://grafana.ripple-transfer.dev/
    prometheus:
      enabled: true
      remoteWrite:
        - url: http://mimir-gateway.mimir.svc.cluster.local:80/api/v1/push
    # TODO: Is there a way to link Tempo here instead?
    jaegerUrl: jaeger.linkerd-jaeger:16686
